export var NetworkMap = {

'Arts': {'icon': "arts", 'color': "#a5203e" },
'Buddhism': {'icon': "buddhism", 'color': "#fcda3f" },
'Business as Mission': {'icon': "business_as_mission", 'color': "#0b7760" },
'Children and Evangelism': {'icon': "evangelism_among_children", 'color': "#b170af" },
'Children at Risk': {'icon': "children_at_risk", 'color': "#ffba00" },
'Church Planting': {'icon': "church_planting", 'color': "#98ce79" },
'Church Research': {'icon': "church", 'color': "#dd9933" },
'Cities': {'icon': "cities", 'color': "#a1ddf7" },
'Creation Care': {'icon': "creation_care", 'color': "#0b7760" },
'Diasporas': {'icon': "diaspora", 'color': "#a49d9a" },
'Disability Concerns': {'icon': "disability_concerns", 'color': "#ff6e00" },
'Freedom and Justice': {'icon': "freedom_and_justice", 'color': "#e64a49" },
'Health in Mission': {'icon': "health-in-missions", 'color': "#6cc8cb" },
'Hinduism': {'icon': "hinduism", 'color': "#ee373c" },
'Integral Mission': {'icon': "integral_mission", 'color': "#eb3c97" },
'Integrity and Anti-Corruption': {'icon': "integrity_and_anticorruption", 'color': "#247ebf" },
'International Student Ministries': {'icon': "international_studeny_ministry", 'color': "#aa6654" },
'Islam': {'icon': "islam", 'color': "#0e946a" },
'Jewish Evangelism': {'icon': "jewish_evangelism", 'color': "#3d81de" },
'Leadership Development': {'icon': "leadership_development", 'color': "#0f5981" },
'Least Evangelized Peoples': {'icon': "least_evangelized_people", 'color': "#8761aa" },
'Marketplace Ministry': {'icon': "marketplace_ministry", 'color': "#f57c20" },
'Media Engagement': {'icon': "media_engagement", 'color': "#231f1d" },
'Men and Women in Partnership for the Gospel': {'icon': "partnership_of_men_and_women", 'color': "#81a25d" },
'foo': {'icon': "care_and_counsel_as_mission", 'color': "#b4c2dc" },
'Resource Mobilization': {'icon': "resource_mobilization", 'color': "#68c8cc" },
'Ministry Partnerships and Networking': {'icon': "strategic_evangelistic_partnerships", 'color': "#772774" },
'Orality': {'icon': "orality", 'color': "#116d84" },
'Evangelism Training and Personal & Small Group Evangelism': {'icon': "evangelism_training", 'color': "#0e406c" },
'Proclamation Evangelism': {'icon': "proclamation_evangelism", 'color': "#ff5700" },
'Reconciliation': {'icon': "reconciliation", 'color': "#c15f4a" },
'Religious Liberty': {'icon': "religious_liberty", 'color': "#aa9075" },
'Scripture Engagement': {'icon': "scripture_engagement", 'color': "#5d4946" },
'Study of Global Christianity': {'icon': "study_of_global_christianity", 'color': "#3ea5dc" },
'Technology': {'icon': "technology", 'color': "#247ebf" },
'Tentmaking': {'icon': "tentmaking", 'color': "#6a3b39" },
'Women in Evangelism': {'icon': "women_in_evangelism", 'color': "#f37f91" },
}
